In [ ]:
"""Python program to import a CSV into DataFrame. Connect to MariaDB that is in the same virtual machine localhost
Create a database cip_proj1. Create a table college_data and insert all rows from the dataframe into the MariaDB table.
Connect to the database and query the table to confirm all the 571 records are stored in the table"""

import pandas as pd
import mysql.connector as msql
from mysql.connector import Error

# Import csv into a dataframe using pandas
df = pd.read_csv('college_popular.csv', index_col=False, delimiter = ',')
df.head()

# Establish connection between Python and MariaDB local database server using mysql and create Database
try:
    conn = msql.connect(host='localhost', database='cip_proj', user='root', password='mariadb')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("CREATE DATABASE cip_proj1")
        print("Database is created")
except Error as e:
    print("Error while connecting to MySQL", e)

# Create table into the new database and insert the rows by looping through the data frame
try:
    conn = msql.connect(host='localhost', database='cip_proj1', user='root', password='mariadb')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS college_data;')
        print('Creating table..')
        #Create table statement 
        cursor.execute ("CREATE TABLE college_data(Rank int, School varchar(255), StudenttoFac varchar(25), Graduation_Rate varchar(25) , Retention_Rate varchar(25) , Acceptance_Rate varchar(25),Enrollment_Rate varchar(25), Instit_Rate varchar(25), Default_Rate varchar(25))")
        print ("Table is created ...") 
        #loop through the data frame
        for i,row in df.iterrows():
            #here %S means string values 
            sql = "INSERT INTO cip_proj1.college_data VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)"
            cursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not auto committed by default, so we must commit to save our changes
            conn.commit()
        print("All rows imported...")        
except Error as e:
            print("Error while connecting to MariaDB mySQL", e)
        
# Execute query the MariaDB database

print("Print all rows from MariaDB Database...")
sql = "SELECT * FROM cip_proj.college_data"
cursor.execute(sql)
# Fetch all the records
result = cursor.fetchall()
for i in result:
    print(i)